### ISSUE TITLE
MPN for battery spring on clamp board is missing

### ISSUE THREAD

**Issue by bvkuik** [offgridsystems/PCB-Clamp-Board#1]
I'm looking for the MPN of those battery spring contacts :)

**Comment by offgridsystems** [comment]
Sorry bvkuik, that is a custom part since I could not find a single spring in the world that worked for DKblock, and believe me I tried very very hard! So I give you the drawings to make that part at https://github.com/offgridsystems/Documents/tree/master/DKblock%20Spring%20contact%20OSHW
and I since I have some stock in the part also, I can put them up on ebay for something near cost of say a lot of 20 for 5 bucks including shipping. Also thank you I did not notice the current Bill of Materials was missing also, so that has been added to the repo. Thank you very much!
